version: '3.4'

services:
  analytics-service:
    environment:
      - NODE_ENV=development
      - MYSQL_DATABASE=analytics
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=admin
    ports:
      - 3000:3000

  mysql:
    environment:
      - MYSQL_DATABASE=analytics
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306
