version: '3.4'

services:
  analytics-service:
    container_name: analytics-service
    build:
      context: .
      target: dependencies
      dockerfile: Dockerfile
    image: analytics-service:dev
    command: npm run debug
    volumes:
      - ./:/opt/analytics-service
      - ./package.json:/opt/analytics-service/package.json
      - ./package-lock.json:/opt/analytics-service/package-lock.json
      - /opt/analytics-service/node_modules
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
